"""Add guild and user language settings

Revision ID: a23f95225939
Revises: 
Create Date: 2026-08-01 17:31:41.650034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23f95225939'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages_guild',
    sa.Column('guild_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('language', sa.Enum('de', 'en', name='supportedlanguage', length=8), server_default='en', nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('languages_user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('language', sa.Enum('de', 'en', name='supportedlanguage', length=8), server_default='en', nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages_user')
    op.drop_table('languages_guild')
    # ### end Alembic commands ###
