#                       THIS FILE INCLUDES SOME USED HARD LIMITS FROM DISCORD'S API.
#       To avoid changing these values everywhere in the project and because some of it is not documented,
#           we store them here to easily adjust it later and to use it as a guide for what is possible.


# Messages
MAX_MESSAGE_CONTENT: int = 2000
MAX_MESSAGE_FILES: int = 10

# Select / Dropdown
MAX_SELECT_ITEMS: int = 25
MAX_SELECT_PLACEHOLDER: int = 150
MAX_SELECT_OPTION_LABEL: int = 100
MAX_SELECT_OPTION_VALUE: int = 100
MAX_SELECT_OPTION_DESCRIPTION: int = 100

# Button
MAX_BUTTON_LABEL: int = 80
MAX_BUTTON_CUSTOM_ID: int = 100
MAX_BUTTON_URL: int = 512

# Modals
MAX_MODAL_TITLE: int = 45
MAX_MODAL_TEXTINPUT: int = 4000
MAX_MODAL_TEXTINPUT_PLACEHOLDER: int = 100
MAX_MODAL_FILEUPLOAD_FILES: int = 10
MAX_MODAL_RADIOBUTTON_OPTIONS: int = 10
MAX_MODAL_RADIOBUTTON_LABEL: int = 100
MAX_MODAL_RADIOBUTTON_VALUE: int = 100
MAX_MODAL_RADIOBUTTON_DESCRIPTION: int = 100
MAX_MODAL_CHECKBOX_OPTIONS: int = 10
MAX_MODAL_CHECKBOX_LABEL: int = 100
MAX_MODAL_CHECKBOX_VALUE: int = 100
MAX_MODAL_CHECKBOX_DESCRIPTION: int = 100

# Embed
MAX_EMBED_COUNT: int = 10
MAX_EMBED_TITLE: int = 256
MAX_EMBED_DESCRIPTION: int = 4096
MAX_EMBED_URL: int = 2048
MAX_EMBED_FIELDS: int = 25
MAX_EMBED_FIELD_NAME: int = 256
MAX_EMBED_FIELD_VALUE: int = 1024
MAX_EMBED_FOOTER_TEXT: int = 2048
MAX_EMBED_AUTHOR_NAME: int = 256
MAX_EMBED_GLOBAL_TEXT: int = 6000  # TOTAL AMOUNT OF TEXT INSIDE OF ALL (MESSAGE) EMBEDS AND FIELDS TOGETHER.

# Webhook
MAX_WEBHOOK_USERNAME: int = 80
MAX_WEBHOOK_AVATARURL: int = 2048

# Threads
MAX_THREADS_NAME: int = 100

# Files
MAX_FILE_SIZE: int = 10485760
