from sqlalchemy import BigInteger
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column

from core.db.base import Base
from core.enums.language import DEFAULT_LANGUAGE, SupportedLanguage


class GuildLanguage(Base):
    """Per-guild bot configuration.

    One row per Discord guild, keyed by its snowflake ID. `guild_id` is not
    auto-incrementing since it is always supplied explicitly (the Discord
    guild ID itself), never generated by the database.
    """

    __tablename__ = "languages_guild"

    guild_id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=False)
    language: Mapped[SupportedLanguage] = mapped_column(
        SQLEnum(
            SupportedLanguage,
            native_enum=True,
            length=8,
            values_callable=lambda enum_cls: [member.value for member in enum_cls],
        ),
        default=DEFAULT_LANGUAGE,
        server_default=DEFAULT_LANGUAGE.value,
        nullable=False,
    )
